### ISSUE TITLE
I-JEPAをImageCuriosityAgentに組み込む

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami-vconf24#64]
# タスク内容

I-JEPAをImage Curiosity Agentで用いられるように、モデルコンポーネント、コンフィグ類を作成する。

### Stacked Features
I-JEPAの埋め込み観測空間は (patch, features) という形状のため、Forward Dynamicsや Policy, Valueでそれを扱えるようにすることが必要である。
そこで、 `policy_value_common_net.py`に記述されている `LerpStackedHidden`レイヤーを用いる。
そのままでは依存関係がスパゲティになるので、 `models/components/stacked_features.py`というファイルに`LerpStackedFeatures`というクラスで再実装し、 LerpStackedHiddenはそのエイリアスとして置き換える。

また、 stackされた featuresも出力できる `ToStackedFeatures`というレイヤーも実装する。

これは個別のPRとして送信する。

### モデル構成

観測が Stacked Featuresになったため、 Policy, Value, Forward Dynamicsの Observation Projectionは `LerpStackedFeatures`を用いる。
また、Forward DynamicsのObservation Headは `ToStackedFeatures`と`NormalMixture`を`nn.Sequential`で結合したものとする。

また、そのままの I-JEPAは小規模なAMIで用いるには大きすぎるため、 モデルサイズの縮小を図る。潜在空間を入力画像の1/10 ~ 1/20にすることを構想している。

### 修正

すでに実装していた `i_jepa_encoder_infer`のflatten処理を削除する。また、`bool_mask_i_jepa.py`と`i_jepa.py`に同じ実装が存在しているため、 `i_jepa.py`のものを`bool_mask_i_jepa.py`にimportしてエイリアスとすることとする。

### 達成条件

- [ ] stacked_features.pyの実装とテスト、PR
- [ ] configの作成
- [ ] 実動作テスト

**Comment by myxyy** [comment]
ForwardDynamicsにLerpStackedHiddenで圧縮した観測を突っ込むのはいいんですが、ForwardDynamicsの予測対象はLerpStackedHiddenで圧縮した表現ではなく、素のI-JEPAの潜在表現になるのでしょうか？

**Comment by Geson-anko** [comment]
@myxyy そうじゃないですかね。
